-- Crie este esquema executando no SQL Editor do seu painel do Supabase

-- Tabela de Produtos
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  ean text unique,
  category text,
  laboratory text,
  average_selling_price numeric
);

-- Tabela de Fornecedores
create table public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  contact text,
  payment_terms text,
  delivery_time text
);

-- Tabela de Cotações
create table public.quotations (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade not null,
  supplier_id bigint references public.suppliers(id) on delete cascade not null,
  price numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- View para facilitar a leitura da cotação no frontend (join automático)
create view public.quotations_view as
select 
  q.id,
  q.price,
  q.created_at,
  q.product_id,
  p.name as product_name,
  p.ean as product_ean,
  q.supplier_id,
  s.name as supplier_name
from quotations q
join products p on q.product_id = p.id
join suppliers s on q.supplier_id = s.id;

-- Tabela de Pedidos Concluídos (histórico de compras)
create table public.orders (
  id bigint generated by default as identity primary key,
  total_cost numeric not null default 0,
  total_savings numeric not null default 0,
  items_count integer not null default 0,
  details jsonb, -- JSON com detalhes dos itens e fornecedores
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
